### PR TITLE
Don't demote master if failed to update leader key in pause

### PR DESCRIPTION
**Pull request by CyberDem0n**
Fixes https://github.com/zalando/patroni/issues/659

### CODE REVIEW

**Comment by alexeyklyukin** [comment]
👍

**Comment by AntonTumasov** [comment]
It works fine, when we imitated network disruption this check passed and logger said proper message during cluster being in maintenance mode. But if we set `resume` master crashes and not coming back after DSC availability is back. 
Logs are just output this:
```Apr 25 16:06:50  python[14578]: 2018-04-25 16:06:50,587 ERROR: get_postgresql_status
Apr 25 16:06:50  python[14578]: Traceback (most recent call last):
Apr 25 16:06:50  python[14578]: File "/opt/patroni/lib/python2.7/site-packages/patroni/api.py", line 432, in get_postgresql_status
Apr 25 16:06:50  python[14578]: self.server.patroni.postgresql.lsn_name), retry=retry)[0]
Apr 25 16:06:50  python[14578]: File "/opt/patroni/lib/python2.7/site-packages/patroni/api.py", line 409, in query
Apr 25 16:06:50  python[14578]: return self.server.query(sql, *params)
Apr 25 16:06:50  python[14578]: File "/opt/patroni/lib/python2.7/site-packages/patroni/api.py", line 487, in query
Apr 25 16:06:50  python[14578]: raise PostgresConnectionException('connection problems')
Apr 25 16:06:50  python[14578]: PostgresConnectionException: 'connection problems'

**Comment by AntonTumasov** [comment]
>How can you resume it if DCS is not accessible?

We restored DCS and it's available again. Then we resume cluster and get the exact same error over and over again. 
>The same problem as before. Logs you are providing are not enough to figure out what is going on.

These are only logs we can get from daemon

**Comment by AntonTumasov** [comment]
This is that happens on master when we click `resume` cluster after DCS is being restored.
```Apr 25 16:38:08  python[14578]: Traceback (most recent call last):
Apr 25 16:38:08  python[14578]: File "/opt/patroni/lib/python2.7/site-packages/patroni/api.py", line 432, in get_postgresql_status
Apr 25 16:38:08  python[14578]: self.server.patroni.postgresql.lsn_name), retry=retry)[0]
Apr 25 16:38:08  python[14578]: File "/opt/patroni/lib/python2.7/site-packages/patroni/api.py", line 409, in query
Apr 25 16:38:08  python[14578]: return self.server.query(sql, *params)
Apr 25 16:38:08  python[14578]: File "/opt/patroni/lib/python2.7/site-packages/patroni/api.py", line 487, in query
Apr 25 16:38:08  python[14578]: raise PostgresConnectionException('connection problems')
Apr 25 16:38:08  python[14578]: PostgresConnectionException: 'connection problems'
Apr 25 16:38:09  python[14578]: 2018-04-25 16:38:09,148 INFO: establishing a new patroni connection to the postgres cluster
Apr 25 16:38:10  python[14578]: 2018-04-25 16:38:10,850 INFO: establishing a new patroni connection to the postgres cluster
Apr 25 16:38:12  python[14578]: 2018-04-25 16:38:12,089 INFO: establishing a new patroni connection to the postgres cluster
Apr 25 16:38:13  python[14578]: 2018-04-25 16:38:13,397 INFO: establishing a new patroni connection to the postgres cluster
Apr 25 16:38:14  python[14578]: 2018-04-25 16:38:14,466 INFO: establishing a new patroni connection to the postgres cluster
Apr 25 16:38:15  python[14578]: 2018-04-25 16:38:15,739 INFO: establishing a new patroni connection to the postgres cluster
Apr 25 16:38:17  python[14578]: 2018-04-25 16:38:17,229 INFO: establishing a new patroni connection to the postgres cluster
Apr 25 16:38:17  python[14578]: 2018-04-25 16:38:17,309 ERROR: get_postgresql_status
Apr 25 16:38:17  python[14578]: Traceback (most recent call last):
Apr 25 16:38:17  python[14578]: File "/opt/patroni/lib/python2.7/site-packages/patroni/api.py", line 432, in get_postgresql_status
Apr 25 16:38:17  python[14578]: self.server.patroni.postgresql.lsn_name), retry=retry)[0]
Apr 25 16:38:17  python[14578]: File "/opt/patroni/lib/python2.7/site-packages/patroni/api.py", line 409, in query
Apr 25 16:38:17  python[14578]: return self.server.query(sql, *params)
Apr 25 16:38:17  python[14578]: File "/opt/patroni/lib/python2.7/site-packages/patroni/api.py", line 487, in query
Apr 25 16:38:17  python[14578]: raise PostgresConnectionException('connection problems')
Apr 25 16:38:17  python[14578]: PostgresConnectionException: 'connection problems'
Apr 25 16:38:17  python[14578]: 2018-04-25 16:38:17,345 ERROR: get_postgresql_status
Apr 25 16:38:17  python[14578]: Traceback (most recent call last):
Apr 25 16:38:17  python[14578]: File "/opt/patroni/lib/python2.7/site-packages/patroni/api.py", line 432, in get_postgresql_status
Apr 25 16:38:17  python[14578]: self.server.patroni.postgresql.lsn_name), retry=retry)[0]
Apr 25 16:38:17  python[14578]: File "/opt/patroni/lib/python2.7/site-packages/patroni/api.py", line 409, in query
Apr 25 16:38:17  python[14578]: return self.server.query(sql, *params)
Apr 25 16:38:17  python[14578]: File "/opt/patroni/lib/python2.7/site-packages/patroni/api.py", line 487, in query
Apr 25 16:38:17  python[14578]: raise PostgresConnectionException('connection problems')
Apr 25 16:38:17  python[14578]: PostgresConnectionException: 'connection problems' 
...
...
```
And this is what we get through API request on master
```{"state": "unknown", "database_system_identifier": "6465376767966821354", "role": "replica", "patroni": {"scope": "patroni-5432", "version": "1.4.3"}}```

**Comment by CyberDem0n** [comment]
> This is that happens on master when we click resume cluster after DCS is restored.

Click? How is it possible?

And again, those are the logs from Patroni REST API thread (HAProxy is calling it).

But what I need to see - ALL Patroni logs from the moment before you called `patronictl resume`.
Your cut from logs should be made from the lines containing `PAUSE: ` and up to the lines where Patroni decided to stop postgres and also a few lines after that moment.

**Comment by alexeyklyukin** [comment]
👍

**Comment by CyberDem0n** [comment]
:+1:

**Pull request merged**
