### PR TITLE
Init.d script for Debian

### PR DESCRIPTION
**Pull request by ph223**
Hi!

I just wrote simple init.d script for running Patroni in Debian. It can be useful for someone.

Regards,
Philipp

### CODE REVIEW

**Comment by ph223** [comment]
Good idea. Thank you!  I'l commit it soon.

**Comment by ph223** [comment]
Hello!
Now I just uploaded script with requested reload function, some refactory and actual README.

**Comment by CyberDem0n** [comment]
:+1:

**Comment by alexeyklyukin** [comment]
👍

**Comment by CyberDem0n** [comment]
Merged, thank you!

**Pull request merged**
