### PR TITLE
Add support for ZooKeeper/Exhibitor DCS URI in patronictl ... -d

### PR DESCRIPTION
**Pull request by a1exsh**

### CODE REVIEW

**Comment by a1exsh** [comment]
Well, line 364 seems to be aware of the limitation of `ZooKeeper` class: no recursive delete.  So someone has to implement that first.

**Comment by CyberDem0n** [comment]
Actually Feike is just using dcs.client object, which is not necessary available for different DCS implementations.
So far it's available for  Etcd and ZooKeeper and this client object even has similar interfaces of `delete` method:
```python
KazooClient.delete(self, path, version=-1, recursive=False)
etcd.Client.delete(self, key, recursive=None, dir=None, **kwdargs)
```

So recursive `delete` for ZooKeeper will work as well. But for example it will not work for Consul.
Instead of doing this ugly hack, one should add the new abstract method to the AbstractDCS class, something like `delete_cluster` and implement it in Etcd and ZooKeeper classes.

**Comment by a1exsh** [comment]
@CyberDem0n oh, right: I didn't pay attention to the `.client` indirection.

**Comment by a1exsh** [comment]
In the hindsight: should we have made client a non-public property, i.e. `_client`?

**Comment by a1exsh** [comment]
Last Travis-CI build was cancelled (timeout?).  It is suggested that closing and re-opening the PR can help.

**Comment by alexeyklyukin** [comment]
Yeah, cancelled it yesterday, it was stuck after 1h. Might be something wrong with the tests....

**Comment by CyberDem0n** [comment]
Tests are wrong.
You should run them locally: python setup.py test

**Comment by a1exsh** [comment]
Spotted it: the tests are hanging on python3.  They were green on every commit on python2, which is my default.  *scratches head*

**Pull request merged**
