### PR TITLE
Add wal-e threshold logging

### PR DESCRIPTION
**Pull request by joar**
Add error log for threshold, so that you can see if thresholds were the reason
for ExitCode.FAIL.

### CODE REVIEW

**Comment by CyberDem0n** [comment]
:+1:

**Comment by alexeyklyukin** [comment]
👍

**Comment by CyberDem0n** [comment]
:+1:

**Comment by CyberDem0n** [comment]
:+1:

**Comment by alexeyklyukin** [comment]
👍

**Comment by CyberDem0n** [comment]
Merged, thank you!

**Pull request merged**
