### PR TITLE
Update some descriptions for the REST API endpoints

### PR DESCRIPTION
**Pull request by alago197**
Alexey, I'm not really sure how we should document the "connect:" REST API parameter. I'm proposing this PR for you to review...

### CODE REVIEW

**Comment by alexeyklyukin** [comment]
LGTM, thank you!

**Comment by alexeyklyukin** [comment]
👍

**Comment by CyberDem0n** [comment]
:+1:

**Comment by alexeyklyukin** [comment]
@alago197 merged, thank you!

**Pull request merged**
