### PR TITLE
Fix syntax error when creating users

### PR DESCRIPTION
**Pull request by GuanqunYang193**
fix the [issue](https://github.com/zalando/patroni/issues/2865)

* supported add membership of the specified existing roles when creating the user
* added step in behave test to check the membership created

### CODE REVIEW

**Comment by CyberDem0n** [comment]
To be honest, it was one of the wrong decisions we made 7 years ago when implemented this feature.
The thing is that once `in role` support is fixed someone will try to use it for roles that are also defined in Patroni config, we we will have to resolve dependencies between roles.
It's not a Patroni task to manage users (replication user is an exception) and I would rather remove this feature entirely than spend time on supporting it.

**Comment by GuanqunYang193** [comment]
> > We create users based on the order set by the user.
> 
> That's the point, users are defined in a dictionary and there is no ordering.

So, during the process of reading the config, it won't preserve the order in which users are defined in the config?

**Comment by CyberDem0n** [comment]
> So, during the process of reading the config, it won't preserve the order in which users are defined in the config?

Config is a YAML file, it is processed by a library. The only we have is a data structure that returned from it. And `users` is a dictionary. Even if the order of elements is preserved like in the YAML file that would be an implementation detail that we shouldn't rely on.

> from my perspective, removing these features would require significant changes and could lead to version incompatibility.

removing it is fairly simple:
1. https://github.com/zalando/patroni/blob/25ceb6825741fb3ac6f9e535af4f3336301edbb0/patroni/postgresql/bootstrap.py#L403-L405
2. https://github.com/zalando/patroni/blob/25ceb6825741fb3ac6f9e535af4f3336301edbb0/patroni/config.py#L752-L767
3. Maybe a few lines in unit tests.

From the Patroni side it all backward compatible. Just the `bootstrap.users` and some environment variables will be ignored.

Really, user-management is a complex task and it is not only about creating users when the cluster is created, but also about possibility to add new users during the cluster life time, about removing unused users, and maybe updating passwords. It is not something that Patroni should do.

Last, but not least, there is a post_bootstrap hook, which you can use to do whatever you like when the new cluster is created.

**Comment by GuanqunYang193** [comment]
1. from the official [doc](https://yaml.org/spec/1.2-old/spec.html#id2802662) the order of list in YAML would be kept.
2. It is not a easy change to not support creating users since:
* although we can ignore the config client create, but when they upgrade to our latest version, it would be a huge change for them since they have to find some where to implement the logic.
* how backup restore would be affected? If we ignore the users in backup files, does that means we can not restore from the file anymore?
* yes I notice there is a script can be use, but from [here](https://github.com/zalando/patroni/issues/667), actually is also the issue we have met, the order of running this script limits some functionalities.

Discontinuing support for user creation is a significant change compared to this PR, as it would affect a large number of users. However, this PR is unlikely to have any impact on existing users. I would still recommend that if we are considering discontinuing user creation, we should further discuss what else should be discontinued in terms of user-defined configurations and then implement those changes together. Personally, I really like this feature, as it provides added security and reliability by keeping this logic in the script rather than relying solely on Patroni.

**Comment by CyberDem0n** [comment]
> from the official [doc](https://yaml.org/spec/1.2-old/spec.html#id2802662) the order of list in YAML would be kept.

You are referring to a list, while `bootstrap.users` is a mapping (python dict).

> how could they deal with existing database instances?

Existing? The `bootstrap` section works only when the new cluster is initialized.

> how backup restore would be affected? If we ignore the users in backup files, does that means we can not restore from the file anymore?

Patroni doesn't interfere with backups.

> yes I notice there is a script can be used, but from https://github.com/zalando/patroni/issues/667, actually is also the issue we have met, the order of running this script limits some functionalities.

The issue also says to stick with one of those, users or post_bootstrap.

> Discontinuing support for user creation is a significant change compared to this PR

How removing ~20 lines of code would be a significant change comparing to this PR?

> Personally, I really like this feature, as it is more reliable to rely on Patroni comparing to implementing and running a script.

It is not about running a script, but about having a proper system that manages users. Patroni shouldn't be solving this problem on the first place.

**Comment by GuanqunYang193** [comment]
> > from the official [doc](https://yaml.org/spec/1.2-old/spec.html#id2802662) the order of list in YAML would be kept.
> 
> You are referring to a list, while `bootstrap.users` is a mapping (python dict).
> 
> > how could they deal with existing database instances?
> 
> Existing? The `bootstrap` section works only when the new cluster is initialized.
> 
> > how backup restore would be affected? If we ignore the users in backup files, does that means we can not restore from the file anymore?
> 
> Patroni doesn't interfere with backups.
> 
> > yes I notice there is a script can be used, but from #667, actually is also the issue we have met, the order of running this script limits some functionalities.
> 
> The issue also says to stick with one of those, users or post_bootstrap.
> 
> > Discontinuing support for user creation is a significant change compared to this PR
> 
> How removing ~20 lines of code would be a significant change comparing to this PR?
> 
> > Personally, I really like this feature, as it is more reliable to rely on Patroni comparing to implementing and running a script.
> 
> It is not about running a script, but about having a proper system that manages users. Patroni shouldn't be solving this problem on the first place.

fine, can you create an issue about this and I can implement and submit a PR.

**Comment by GuanqunYang193** [comment]
@hughcapet do you think it is ok to stop supporting user creation or use this PR change to enrich the functionality

**Comment by hughcapet** [comment]
@GuanqunYang193 yes, I do think user management is not Patorni's task and we can remove it in the next major release (preliminarily adding a deprecation warning to the docs and maybe also log warning to the next minor release)

**Pull request closed without merging**
