### PR TITLE
Update docker-compose example to postgres 10

### PR DESCRIPTION
**Pull request by CyberDem0n**
Some other changes are related to the new version of confd, which now requires specifying etcd url instead of etcd host.

### CODE REVIEW

**Comment by alexeyklyukin** [comment]
Did you really intend to downgrade Etcd from 3.2.3 to 3.0.17? Why?

**Comment by CyberDem0n** [comment]
Yes, it's the intentional change. Just because binaries are smaller :)

**Comment by alexeyklyukin** [comment]
@CyberDem0n I see it the other way around, 3.2.3 is ~ 6MB smaller.

```
for ETCDVERSION in 3.0.17 3.2.3; do mkdir -p ${ETCDVERSION} && curl -sL https://github.com/coreos/etcd/releases/download/v${ETCDVERSION}/etcd-v${ETCDVERSION}-linux-amd64.tar.gz|tar xz -C ${ETCDVERSION}  --strip=1 --wildcards --no-anchored etcd etcdctl; done && ls -lah *
3.0.17:
total 38M
drwxr-xr-x 4 okliukin wheel 128 Jul 17 11:29 .
drwxr-xr-x 4 okliukin wheel 128 Jul 17 11:29 ..
-rwxr-xr-x 1 okliukin wheel 20M Jan 20  2017 etcd
-rwxr-xr-x 1 okliukin wheel 18M Jan 20  2017 etcdctl

3.2.3:
total 32M
drwxr-xr-x 4 okliukin wheel 128 Jul 17 11:30 .
drwxr-xr-x 4 okliukin wheel 128 Jul 17 11:29 ..
-rwxr-xr-x 1 okliukin wheel 17M Jul 14  2017 etcd
-rwxr-xr-x 1 okliukin wheel 14M Jul 14  2017 etcdctl
```

**Comment by CyberDem0n** [comment]
That's interesting. Somehow I've got a wrong impression that size is consistently growing.

**Comment by alexeyklyukin** [comment]
👍

**Pull request merged**
