### PR TITLE
Handle missing timelines in history file when deciding to rewind

### PR DESCRIPTION
**Pull request by CyberDem0n**
When restore_command is configured Postgres is trying to fetch/apply all possible WAL segments and also fetch history files in order to select the correct timeline. It could result in a situation where the new history file will be missing some timelines.

Example:
- node1 demotes/crashes on timeline 1
- node2 promotes to timeline 2 and archives `00000002.history` and crashes
- node1 recovers as a replica, "replays" `00000002.history` and promotes to timeline 3

As a result, the `00000003.history` will not have the line with timeline 2, because it never replayed any WAL segment from it.
The `pg_rewind` tool is supposed to correctly handle such case when rewinding node2 from node1, but Patroni when deciding whether the rewind should happen was searching for the exact timeline in the history file from the new primary.

The solution is to assume that rewind is required if the current replica timeline is missing.

In addition to that this PR makes sure that the primary isn't running in recovery before starting the procedure of rewind check.

Close https://github.com/zalando/patroni/issues/2118 and https://github.com/zalando/patroni/issues/2124

### CODE REVIEW

**Comment by fischerman** [comment]
If timeline 2 is missing from the master node1, isn't that reason enough to need a rewind? Why do we still have to compare LSNs?

**Comment by CyberDem0n** [comment]
@fischerman maybe you are right, in this case the fix would be even simpler:
```diff
                 elif parent_timeline > local_timeline:
+                    need_rewind = True
                     break
+            else:  # loop exit without break
+                need_rewind = True
```

**Comment by FxKu** [comment]
:+1:

**Comment by CyberDem0n** [comment]
:+1:

**Pull request merged**
