### PR TITLE
WIP Quorum commit feature #2

### PR DESCRIPTION
**Pull request by anikin-aa**
This a PR for quorum commit feature, based on https://github.com/zalando/patroni/pull/672.

But, with minor changes:

* Only one parameter for quorum `synchronous_quorum` - number of members that should be in sync.
* Complicated `QuorumStateResolver` logic removed.

as described here https://github.com/zalando/patroni/issues/664.

Almost all tests are done (need to add new one, also), work is still in progress.

### CODE REVIEW

**Comment by CyberDem0n** [comment]
It looks like you removed a lot of useful code from the original PR.

It also doesn't follow a specification from [here](https://github.com/zalando/patroni/issues/664#issuecomment-381307309) and [here](https://github.com/zalando/patroni/issues/664#issuecomment-381789441)

**Comment by anikin-aa** [comment]
Yes, I know this. My changes are not so complicated, but they are working. 
May be its acceptable to mark them like `Phase 1` of implementation, or something like that.

**Comment by CyberDem0n** [comment]
Well, let's assume that you have `synchronous_standby_names = 'any 1 ( patroni-0, patroni-1, patroni-2, patroni-3 )'`

That basically means only one node is syncronous, but you don't know which one.
If the primary failed and the only synchronous node also failed, remainig three nodes will successfully elect the new leader and there'll be data loss.

**Comment by anikin-aa** [comment]
Ok, I got You. I've also  done some changes based on @ants code, and its working too. I am interested in such functionality (quorum replication)  in general.
So its better to close this  PR and raise a new one based on @ants code, right ?

Cause I tried to raise PR with my changes to @ants and I have no response from him.

> If the primary failed and the only synchronous node also failed, remainig three nodes will successfully elect the new leader and there'll be data loss.

Anyway, I can't get  how @ants logic will prevent from such situations

**Comment by CyberDem0n** [comment]
> Anyway, I can't get how @ants logic will prevent from such situations

[_is_healthiest_node](https://github.com/zalando/patroni/pull/672/files#diff-57c53e988b775ee2902488fb33c1f433R511) is taking care of it.

**Pull request closed without merging**
