### PR TITLE
Behave tests on Windows

### PR DESCRIPTION
**Pull request by CyberDem0n**
Windows doesn't support `SIGTERM`, but our behave tests in majority of cases relying on Patroni graceful shutdown.
In order to emulate the behaviour we introduced the new REST API endpoint `POST /sigterm`. The endpoint works only on Windows and when `BEHAVE_DEBUG` environment variable is set.
Besides that some minor adjustments in behave tests were done. Mainly related to backslash-slash handling.

In addition to that improve test coverage on Windows by properly mocking access to filesystem and avoiding calling
 `subprocess.call()`. Specifically, symlink creation on Windows requires Admin privileges and there is no `true.exe`.

### CODE REVIEW

**Comment by hughcapet** [comment]
Nice to see we finally have such an experienced Patroni hacker, who runs it on Windows :)

**Comment by hughcapet** [comment]
👍

**Comment by hughcapet** [comment]
👍

**Comment by idanovinda** [comment]
👍

**Pull request merged**
