### PR TITLE
#694 handle configuration error

### LINKED ISSUE #694: Fails with error on start
Patroni terminates with the following error messages on startup:

 2018-06-05 21:41:41,692 INFO: Selected new etcd server http://192.168.221.45:2379
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/patroni/__init__.py", line 176, in main
    return patroni_main()
  File "/usr/local/lib/python2.7/dist-packages/patroni/__init__.py", line 143, in patroni_main
    patroni = Patroni()
  File "/usr/local/lib/python2.7/dist-packages/patroni/__init__.py", line 30, in __init__
    self.api = RestApiServer(self, self.config['restapi'])
  File "/usr/local/lib/python2.7/dist-packages/patroni/api.py", line 476, in __init__
    self.__initialize(config)
  File "/usr/local/lib/python2.7/dist-packages/patroni/api.py", line 520, in __initialize
    host, port = config['listen'].rsplit(':', 1)
ValueError: need more than 1 value to unpack

I have the following setup:

- Fresh Ubuntu 18.04 (running in LXD containers)
- stock postgreSQL
- followed the instructions on [linode.com:](https://www.linode.com/docs/databases/postgresql/create-a-highly-available-postgresql-cluster-using-patroni-and-haproxy/)

PS: I had a version conflict warning in this setup: 

/usr/local/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!

which I've found a work around for:

pip uninstall requests
pip install requests
pip uninstall docopt
pip install docopt

Source: [here](https://medium.com/@gloriapalmagonzalez/urllib3-1-22-or-chardet-2-2-1-doesnt-match-a-supported-version-requestsdependencywarning-97c36e0cb561)

No effect on the above error though

### PR DESCRIPTION
**Pull request by hjacobs**
Fixes #694 by handling a configuration error with a more friendly failure message.

### CODE REVIEW

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
@CyberDem0n thanks! I was not aware of this runtime reloading feature.

**Comment by alexeyklyukin** [comment]
👍

**Comment by CyberDem0n** [comment]
:+1:

**Pull request merged**
