### PR TITLE
Use "spawn" multiprocessing start method to workaround https://bugs.python.org/issue6721

### LINKED ISSUE #1278: Postmaster starting process hangs because sys.stderr is locked after fork
In version `v1.6.0` Patroni uses forking `multiprocessing.Process` for creating a postmaster parent.
Unfortunately there are other threads which may hold some locks during `fork()` call.

```
$ docker-compose exec patroni2 ps xaf
  PID TTY      STAT   TIME COMMAND
  382 pts/0    Rs+    0:00 ps xaf
    1 ?        Ss     0:00 python3 /patroni.py postgres0.yml
    8 ?        Sl     0:00 python3 /patroni.py postgres0.yml
   24 ?        Ss     0:00  \_ python3 /patroni.py postgres0.yml
   25 ?        S      0:00      \_ postgres -D /var/lib/postgresql/data/pgdata -
   26 ?        Ss     0:00          \_ postgres: batman: startup process   recov
   27 ?        Ss     0:00          \_ postgres: batman: checkpointer process   
   28 ?        Ss     0:00          \_ postgres: batman: writer process   
   29 ?        Ss     0:00          \_ postgres: batman: stats collector process
   31 ?        Ss     0:00          \_ postgres: batman: postgres postgres 127.0
```
The postmaster parent hangs on lock on stderr:
```
Thread 0x7fbf86ffd700
  File "/usr/lib/python3.5/threading.py", line 882, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/patroni/async_executor.py", line 97, in run
    wakeup = func(*args) if args else func()
  File "/patroni/postgresql/__init__.py", line 728, in follow
    self.start(timeout=timeout, block_callbacks=change_role, role=role)
  File "/patroni/postgresql/__init__.py", line 434, in start
    options)
  File "/patroni/postgresql/postmaster.py", line 175, in start
    proc.start()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 267, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 74, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 269, in _bootstrap
    sys.stderr.flush()
  File "<string>", line 1, in <module>
  File "<string>", line 7, in <module>
```
While a bootstrap thread waits for child to finish:
```
Thread 0x7fbf86ffd700
  File "/usr/lib/python3.5/threading.py", line 882, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/patroni/async_executor.py", line 97, in run
    wakeup = func(*args) if args else func()
  File "/patroni/postgresql/__init__.py", line 728, in follow
    self.start(timeout=timeout, block_callbacks=change_role, role=role)
  File "/patroni/postgresql/__init__.py", line 434, in start
    options)
  File "/patroni/postgresql/postmaster.py", line 177, in start
    proc.join()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 121, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 51, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 29, in poll
    pid, sts = os.waitpid(self.pid, flag)
```

The hanging patroni process repeatedly logs: `INFO: restarting after failure in progress`.

It is a known issue in Python that threading and multiprocessing do not mix well: [https://bugs.python.org/issue6721](url)
While the issue with logging lock might have been fixed in Python 3.7 the recommended workaround is to use `spawn` of `forkserver` start methods, e.g. by adding `multiprocessing.set_start_method('spawn')` at the beggining of `main()`.

This can be quickly reproduced using following `docker-compose.yml`:
```
version: "2.1"
volumes:
    patroni1_volume:
    patroni2_volume:
services:
    zookeeper:
        image: zookeeper:3.4.10
    patroni1:
        build:
          context: https://github.com/zalando/patroni.git
        depends_on:
            - zookeeper
        environment:
            PATRONI_POSTGRESQL_DATA_DIR: /var/lib/postgresql/data/pgdata
            PATRONI_ZOOKEEPER_HOSTS: "[\"zookeeper:2181\"]"
        volumes:
            - patroni1_volume:/var/lib/postgresql/data
        healthcheck:
            test: "curl --fail localhost:8008/health && (curl --fail localhost:8008/sync || curl --fail localhost:8008/master)"
            interval: 10s
            timeout: 5s
            retries: 30
    patroni2:
        build:
          context: https://github.com/zalando/patroni.git
        depends_on:
            - zookeeper
        environment:
            PATRONI_POSTGRESQL_DATA_DIR: /var/lib/postgresql/data/pgdata
            PATRONI_ZOOKEEPER_HOSTS: "[\"zookeeper:2181\"]"
        volumes:
            - patroni2_volume:/var/lib/postgresql/data
        healthcheck:
            test: "curl --fail localhost:8008/health && (curl --fail localhost:8008/sync || curl --fail localhost:8008/master)"
            interval: 10s
            timeout: 5s
            retries: 30
```
and following shell script:
```
#!/bin/bash
docker-compose up -d
docker-compose exec patroni1 patronictl edit-config -s synchronous_mode=true -q --force batman
CHECK() { ! docker-compose ps  | grep patroni[12] | tee /dev/stderr | grep -v '(healthy)' > /dev/null; }
WAIT() { for ((i=0;i<300;i++)); do ! CHECK || break; sleep 1; done; CHECK; }
while WAIT; do docker-compose restart patroni{1,2}; done
```

### PR DESCRIPTION
**Pull request by maciejkowalczyk9ld**
Fixes #1278

### CODE REVIEW

**Comment by maciejkowalczyk9ld** [comment]
The  #1278 seems to no longer reproduce using the scenario provided there

**Comment by CyberDem0n** [comment]
Please also fix the formatting: https://travis-ci.org/zalando/patroni/jobs/611966144#L1257

**Comment by avaczi** [comment]
:+1:

**Comment by CyberDem0n** [comment]
:+1:

**Comment by CyberDem0n** [comment]
Merged, thank you @maciejkowalczyk9ld

**Pull request merged**
