### PR TITLE
Release/v3.2.1

### PR DESCRIPTION
**Pull request by CyberDem0n**
- bump version
- bump pyright
- update release notes

### CODE REVIEW

**Comment by CyberDem0n** [comment]
@barthisrael this is a bugfix release, I cherry picked only bugfixes to REL_3_2 branch. That is, `barman_recover_command` is not included.

**Comment by barthisrael** [comment]
> @barthisrael this is a bugfix release, I cherry picked only bugfixes to REL_3_2 branch. That is, `barman_recover_command` is not included.

🤦 

I tried looking at the commit history, but I selected the wrong branch (`release/v3.2.1` instead of `REL_3_2`) -- sorry!

**Comment by barthisrael** [comment]
👍

**Comment by hughcapet** [comment]
👍

**Pull request merged**
