### PR TITLE
Update REWIND_USERNAME,PASSWORD optional tag in ENVIRONMENT.rst file

### PR DESCRIPTION
**Pull request by htsnorman**
Update REWIND_USERNAME, REWIND_PASSWORD optional tag in ENVIRONMENT.rst file

### CODE REVIEW

**Comment by hughcapet** [comment]
It probably also makes sense to mention the optionality of the rewind user [here](https://github.com/zalando/patroni/blob/master/docs/SETTINGS.rst#postgresql)?

**Comment by hughcapet** [comment]
@htsnorman would you mind updating `SETTINGS.rst` as well?

**Comment by htsnorman** [comment]
@hughcapet done

**Comment by CyberDem0n** [comment]
:+1:

**Comment by hughcapet** [comment]
👍

**Pull request merged**
