### PR TITLE
Docs / README - mention currently supported PostgreSQL versions

### PR DESCRIPTION
**Pull request by kmoppel**
Hi,
I think would make sense to hightlight supported PG versions more prominently...lot of questions on that somehow from our customers. Currently one needs to dive into the Issues history to get some clues...

### CODE REVIEW

**Comment by bradnicholson** [comment]
Even though Patroni works with older versions, would it make more sense to take a support stance that Patroni officially supports the currently supported versions of Postgres?  Seems like it would be nice to mirror those and drop off support for older versions.

**Comment by kmoppel** [comment]
Sure, if Patroni project's policy is to follow the official Postgres support window then this would of course be the message here...so the question is I guess if there's a support strategy and are there some automatic tests covering only last version etc. ...@CyberDem0n you probably have some input here? :)

**Comment by CyberDem0n** [comment]
There is no big value in removing support of PostgreSQL versions which are EOL.
The only problem with legacy, that they are not covered by behave tests.
Support 14devel is a bit too ambitious, it is better to stop at 13 :)

**Comment by kmoppel** [comment]
@CyberDem0n ok probably a good idea - although I checked that 14devel works things might still change there too much...

**Comment by CyberDem0n** [comment]
:+1:

**Comment by FxKu** [comment]
:+1:

**Comment by CyberDem0n** [comment]
Merged, thank you @kmoppel.

**Pull request merged**
