### PR TITLE
Improve patronictl reinit

### PR DESCRIPTION
**Pull request by CyberDem0n**
Make it possible to cancel a running task if you want to reinitialize replica.
There are two possible ways to trigger it:
1. patronictl will ask whether you want to cancel already running task if an attempt to trigger reinitialize has failed
2. if you are using `--force` argument with `patronictl reinit`

### CODE REVIEW

**Comment by alexeyklyukin** [comment]
👍

**Comment by alexeyklyukin** [comment]
LGTM. Perhaps it makes sense to emit the log entry when the task has been forcefully cancelled in order to simplify the task of someone trying to figure out what has happened by looking at the logs. Also, there are some spelling issues with variable names (cancellable/cancelled).

**Comment by alexeyklyukin** [comment]
👍

**Comment by CyberDem0n** [comment]
:+1:

**Pull request merged**
