### PR TITLE
Add warning to the sample config about bootstrap section

### PR DESCRIPTION
**Pull request by CyberDem0n**
it often people are trying to change it and coming with the questions why it doesn't work.

### CODE REVIEW

**Comment by hughcapet** [comment]
👍

**Comment by CyberDem0n** [comment]
:+1:

**Comment by barthisrael** [comment]
I wonder if we should also add such a warning when generating a sample config file through the feature that @hughcapet developed?

**Comment by hughcapet** [comment]
seems adding comment lines with pyyaml is not straightforward enough to do it right now:)

**Pull request merged**
