### PR TITLE
Constant time comparison of auth key

### PR DESCRIPTION
**Pull request by alexbrasetvik**
… to avoid [timing attacks](https://codahale.com/a-lesson-in-timing-attacks/).

### CODE REVIEW

**Comment by alexbrasetvik** [comment]
You beat me to it. :) Your fix seems to appease the 2.7 builds and LGTM 👍

**Comment by sdudoladov** [comment]
:+1:

**Comment by CyberDem0n** [comment]
:+1:

**Comment by CyberDem0n** [comment]
Merged, thank you @alexbrasetvik!

**Pull request merged**
