### PR TITLE
Fixing grammar and typos

### PR DESCRIPTION
**Pull request by mamercad**
subj, and a few more words to make zappr happy

### CODE REVIEW

**Comment by mamercad** [comment]
Let me know if you'd like an issue for this please.

**Comment by CyberDem0n** [comment]
Tests sometimes failing due to the slowenes of GH Actions workers :(
Retrigger fixed it.

**Comment by hjacobs** [comment]
:+1:

**Comment by CyberDem0n** [comment]
:+1:

**Pull request merged**
