### PR TITLE
Update cacert documentation for use with REST API

### LINKED ISSUE #1188: Documentation for rest api yaml does not include cacert property
The documentation for the rest API section of the yaml file doesn't include the 'cacert' property, meaning that if a key and cert signed by a CA are provided, patronictl commands such as reinit will fail due to a certificate warning for anyone who doesn't code dive to find out how the request is formed.

### PR DESCRIPTION
**Pull request by geokala**
Fixes #1188

### CODE REVIEW

**Comment by Jan-M** [comment]
:+1:

**Comment by CyberDem0n** [comment]
:+1:

**Comment by CyberDem0n** [comment]
Merged, thank you!

**Comment by geokala** [comment]
Great, thanks!

**Pull request merged**
