### PR TITLE
Find and load dcs class implementations dynamically

### PR DESCRIPTION
**Pull request by CyberDem0n**
In order to achieve that I've created `patroni.dcs` package and moved necessary files into it.

### CODE REVIEW

**Comment by alexeyklyukin** [comment]
👍

**Comment by alexeyklyukin** [comment]
Actually, from here there is one step to making DCS truly pluggable (i.e. the senza guys did it with https://github.com/zalando-stups/senza/pull/212/files).

**Comment by feikesteenbergen** [comment]
+1

**Comment by feikesteenbergen** [comment]
+1

**Comment by feikesteenbergen** [comment]
+1

**Comment by feikesteenbergen** [comment]
👍

**Comment by feikesteenbergen** [comment]
+1

**Pull request merged**
