### PR TITLE
Always send token in the X-Consul-Token http header

### PR DESCRIPTION
**Pull request by CyberDem0n**
Fixes https://github.com/zalando/patroni/issues/552

### CODE REVIEW

**Comment by DeathBorn** [comment]
This works

**Comment by DeathBorn** [comment]
One more thing. Since this is towards consul, there should be another parameter for configuration. That is ```dc```
Please add 'dc' to https://github.com/zalando/patroni/blob/d15e8ffc87d81d9f56777e6cca0594d613e44716/patroni/dcs/consul.py#L149

**Comment by alexeyklyukin** [comment]
👍

**Comment by CyberDem0n** [comment]
:+1:

**Pull request merged**
