### PR TITLE
Kubernetes services for Read and Read-Write

### PR DESCRIPTION
**Pull request by karthiksharmasg**
Adding 2 services depending on pod selector for Read and Read-Write operations.

### CODE REVIEW

**Comment by CyberDem0n** [comment]
There is already read-write service: https://github.com/zalando/patroni/blob/master/kubernetes/patroni_k8s.yaml#L113-L124

**Comment by karthiksharmasg** [comment]
@CyberDem0n 
The current service will not point to proper pod after the promotion of a node, hence i have added the role as either "master" or "replica".

**Comment by CyberDem0n** [comment]
>The current service will not point to proper pod after the promotion of a node

Really? How do you run it? Do you have PATRONI_KUBERNETES_USE_ENDPOINTS set to true: https://github.com/zalando/patroni/blob/master/kubernetes/patroni_k8s.yaml#L51-L52?

**Comment by karthiksharmasg** [comment]
Yes, I was able to get the complete cluster up, but after new pod took over the master role post deletion of "old master", this server lost the connection.

**Comment by CyberDem0n** [comment]
> but after new pod took over the master role post deletion of "old master", this server lost the connection

I don't really get it. How you explain "lost the connection"? Any application MUST reconnect after failover or switchover. It is not possible to do it transparently.

**Comment by karthiksharmasg** [comment]
Let me try to explain it in a different way, 

lets take this scenario where i have replica set as 3;
patronidemo-0   role=master
patronidemo-1   role=replica
patronidemo-2   role=replica

We have a default service patronidemo which binds to backend pods by application and cluster-name but not with any role

{
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
        "creationTimestamp": "2019-08-26T08:29:50Z",
        "labels": {
            "application": "patroni",
            "cluster-name": "patronidemo"
        },
        "name": "patronidemo",
        "namespace": "default",
        "resourceVersion": "16116595",
        "selfLink": "/api/v1/namespaces/default/services/patronidemo",
        "uid": "abbbab49-c7db-11e9-892c-005056ad1ff1"
    },
    "spec": {
        "clusterIP": "xx.xx.xx.xx",
        "ports": [
            {
                "port": 5432,
                "protocol": "TCP",
                "targetPort": 5432
            }
        ],
        "sessionAffinity": "None",
        "type": "ClusterIP"
    },
    "status": {
        "loadBalancer": {}
    }
}

these new services make sure that we have a specific service endpoints that reroutes read and read-write operations to master or a replica nodes.

**Comment by CyberDem0n** [comment]
@karthiksharmasg you are not answering my question.

> We have a default service patronidemo which binds to backend pods by application and cluster-name but not with any role

This service will connect you to the master, because Patroni updates the endpoint and puts IP of the master pod into subsets! I am 100% confident that it works correctly, in the opposite case failover wouldn't work.

**Comment by karthiksharmasg** [comment]
@CyberDem0n 
IF that's the case, then post fail over its not adding the IP of the master pod into subsets, let me validate this part before i ask for the spec changes.

**Comment by CyberDem0n** [comment]
1. There is no such thing as post failover
2. The new leader atomically puts it ip into subsets when grabs the leader lock: https://github.com/zalando/patroni/blob/master/patroni/dcs/kubernetes.py#L342.

**Comment by karthiksharmasg** [comment]
Yes, this i understood, let me check my environment why this is not happening.

**Comment by karthiksharmasg** [comment]
@CyberDem0n 
There was a issue with incorrect label definition in the service and hence the endpoint update was not properly read by service, I will close this PR.

**Pull request closed without merging**
