### PR TITLE
GitHub Action to use codespell to discover typos

### PR DESCRIPTION
**Pull request by cclauss**
Mandatory tests are now: bandit, codespell, flake8, pytest
$ `pytest .`
```
============================= test session starts ==============================
platform linux -- Python 3.9.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/runner/work/patroni/patroni
plugins: cov-2.12.1
collected 464 items

tests/test_api.py ............................                           [  6%]
tests/test_async_executor.py ....                                        [  6%]
tests/test_aws.py ....                                                   [  7%]
tests/test_bootstrap.py .........                                        [  9%]
tests/test_callback_executor.py .                                        [  9%]
tests/test_cancellable.py ...                                            [ 10%]
tests/test_config.py ......                                              [ 11%]
tests/test_consul.py ......................                              [ 16%]
tests/test_ctl.py ....................................                   [ 24%]
tests/test_etcd.py ...........................                           [ 30%]
tests/test_etcd3.py .............................                        [ 36%]
tests/test_exhibitor.py ...                                              [ 37%]
tests/test_ha.py ....................................................... [ 48%]
..................................                                       [ 56%]
tests/test_kubernetes.py .............................                   [ 62%]
tests/test_log.py ..                                                     [ 62%]
tests/test_patroni.py ...............                                    [ 66%]
tests/test_postgresql.py ............................................... [ 76%]
....                                                                     [ 77%]
tests/test_postmaster.py .........                                       [ 79%]
tests/test_raft.py ..........                                            [ 81%]
tests/test_raft_controller.py ...                                        [ 81%]
tests/test_rewind.py ............                                        [ 84%]
tests/test_slots.py .......                                              [ 85%]
tests/test_utils.py ............                                         [ 88%]
tests/test_validator.py ........                                         [ 90%]
tests/test_wale_restore.py ......                                        [ 91%]
tests/test_watchdog.py ................                                  [ 95%]
tests/test_zookeeper.py .......................                          [100%]

=============================== warnings summary ===============================
../../../../../opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/boto/plugin.py:40
  /opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/boto/plugin.py:40: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================= 464 passed, 1 warning in 16.53s ========================
```

### CODE REVIEW

**Comment by cclauss** [comment]
Cyclomatic complexity has increased by 10.

**Comment by CyberDem0n** [comment]
@cclauss JFYI, we are not really interested in having the linting workflow, codacy already covering most of it.

**Comment by cclauss** [comment]
Sorry to disagree but I have never seen a use for Codacy -- It catches nothing and is clearly no match for:
* bandit black codespell flake8 isort mypy pytest pyupgrade safety

**Comment by CyberDem0n** [comment]
pytest and flake8 are already executed for every commit.

**Comment by CyberDem0n** [comment]
bandit -- covered by codacy
isort, black -- I don't really want reformatting the code just because the tool wants it.
pyupgrade -- there are still good reasons to keep the code compatible with 2.7 and 3.5. After all it isn't that hard.
mypy -- just plenty of false positives
safety -- already covered by dependabot

That is, from the above list only codespell seems to be interesting.

**Comment by cclauss** [comment]
Cool.  I simplified to be codespell only.

How do you configure Codacy to skip Bandit B101,B104,B105,B108,B110,B310,B311,B404,B602,B603,B607,B608,B609 ?

**Pull request closed without merging**
