### PR TITLE
Fix documentation typo

### PR DESCRIPTION
**Pull request by wilfriedroset**
This PR fixes two small typos in replica bootstrap documentation

### CODE REVIEW

**Comment by wilfriedroset** [comment]
zappr says `PR's body failed check 'contains-issue-number'`.
should I open on issue before fixing the typos?

**Comment by CyberDem0n** [comment]
Just write something meaningful in the body

**Comment by RafiaSabih** [comment]
:+1:

**Comment by CyberDem0n** [comment]
:+1:

**Pull request merged**
