### PR TITLE
Add support for patroni replication user socket connection

### PR DESCRIPTION
**Pull request by melrifa**
Issue: https://github.com/zalando/patroni/issues/1866

### CODE REVIEW

**Review by CyberDem0n — COMMENTED** [review]
There is a typo in the documentation.
Also, I reshuffled code a bit in the resolve_connection_addresses().

**Comment by edysli** [comment]
I've tried this patch and it allows me to work around #1884, using UNIX sockets instead of a TLS connection to localhost for the replication user. :smiley:

**Comment by FxKu** [comment]
:+1:

**Comment by CyberDem0n** [comment]
:+1:

**Pull request merged**
