### PR TITLE
Rename ambiguous `Failover.member` to candidate

### PR DESCRIPTION
**Pull request by CyberDem0n**
But! 'member' is still accepted by REST API and also name 'member' is
used to strore/read this value to/from DCS (for backward comatibility)

### CODE REVIEW

**Comment by alexeyklyukin** [comment]
:+1:

**Comment by alexeyklyukin** [comment]
Actually, I think it rightfully complains that do_failover_result has a parameter candidate that is unused.

**Comment by CyberDem0n** [comment]
I know. Currently `poll_failover_result` method just checks that leader has changed.
But it also should check that leader is matching with the `candidate`.

**Comment by alexeyklyukin** [comment]
:+1:

**Comment by alexeyklyukin** [comment]
+1

**Pull request merged**
