### PR TITLE
Defer TLS handshake until thread has started

### PR DESCRIPTION
**Pull request by CyberDem0n**
The `SSLSocket` is immediately doing the handshake on accept. Effectively it blocks the whole API thread if the client-side doesn't send any data.
In order to solve the issue we defer the handshake until a thread serving request has started.

The solution is a bit hacky, but thread-safe.

Close https://github.com/zalando/patroni/issues/1545

### CODE REVIEW

**Comment by CyberDem0n** [comment]
I have a feeling that it should solve https://github.com/zalando/patroni/issues/1127 and https://github.com/zalando/patroni/issues/857

**Comment by bjh21** [comment]
I've applied this patch on my test system, and it seems to work in minimal testing.

**Comment by bjh21** [comment]
Slightly more testing: I scanned my test cluster with OpenVAS last night and the monitoring worked correctly throughout.

**Comment by CyberDem0n** [comment]
@wilfriedroset, @jpuris, @psuderevsky, @jouir please take a look, highly likely it will solve problems of API freezes when TLS is configured. It would be great if you put it to the test.

**Comment by psuderevsky** [comment]
@CyberDem0n Hi. I encountered this issue only once in a year and actual steps to reproduce are unknown, so it seems that only time will tell, unfortunately.

**Comment by KostyaEsmukov** [comment]
I had 3 freezes in last 2 months on a cluster with TLS enabled so I'm really looking forward for #1127/#857 to be solved.

I have just applied this patch on the problematic cluster. Will let you know if the issue persists.

**Comment by FxKu** [comment]
:+1:

**Comment by CyberDem0n** [comment]
:+1:

**Comment by CyberDem0n** [comment]
:+1:

**Pull request merged**
