### PR TITLE
Create raft data_dir if necessary

### LINKED ISSUE #1760: Create raft data_dir if it does not exist
I think it would be useful to have patroni/patroni_raft_controller create the `data_dir` if it does not exist already. If the user that starts patroni/patroni_raft_controller does not have the rigts to create that directory, that would still be a failure.

This would make setting things up a bit easier.

### PR DESCRIPTION
**Pull request by mamercad**
Fixes #1760 ... maybe 😄

### CODE REVIEW

**Review by CyberDem0n — COMMENTED** [review]
I think it is better to use the existing [validate_directory()](https://github.com/zalando/patroni/blob/9b263dc6c90a3434d8754f454c2ea24304fecd28/patroni/utils.py#L458-L473) function for that.

You can get usage example from https://github.com/zalando/patroni/blob/9b263dc6c90a3434d8754f454c2ea24304fecd28/patroni/postgresql/config.py#L327-L340

Actually, I like the handling of `errno.EEXIST`, it could be incorporated into the validate_directory().

**Comment by mamercad** [comment]
> I think it is better to use the existing [validate_directory()](https://github.com/zalando/patroni/blob/9b263dc6c90a3434d8754f454c2ea24304fecd28/patroni/utils.py#L458-L473) function for that.
> 
> You can get usage example from
> 
> https://github.com/zalando/patroni/blob/9b263dc6c90a3434d8754f454c2ea24304fecd28/patroni/postgresql/config.py#L327-L340
> 
> Actually, I like the handling of `errno.EEXIST`, it could be incorporated into the validate_directory().

Thanks, I'm not very familiar with the code base, didn't realize this function existed.

**Comment by mamercad** [comment]
@CyberDem0n Can you help with the failing check?

**Comment by mamercad** [comment]
> @CyberDem0n Can you help with the failing check?

Oh, strange, guess they're all passing now.

**Comment by CyberDem0n** [comment]
> Oh, strange, guess they're all passing now.

Sometimes they fail due to the slowness of GH Actions workers. Retrigger usually helps.

**Comment by CyberDem0n** [comment]
:+1:

**Comment by FxKu** [comment]
:+1:

**Comment by CyberDem0n** [comment]
Merged, thank you @mamercad!

**Pull request merged**
