### PR TITLE
Single user mode was waiting for user input and never finish

### PR DESCRIPTION
**Pull request by CyberDem0n**
Regression was introduced in https://github.com/zalando/patroni/pull/576

### CODE REVIEW

**Comment by alexeyklyukin** [comment]
Damn, I swear I  'reproduced' this issue live during the tutorial :-) Will take a look today.

**Comment by alexeyklyukin** [comment]
👍

**Comment by Jan-M** [comment]
Is this good to be merged @CyberDem0n ?

**Comment by CyberDem0n** [comment]
:+1:

**Pull request merged**
