### PR TITLE
Always use replication=1, otherwise it is considered a logical walsender

### PR DESCRIPTION
**Pull request by CyberDem0n**
Fixes: https://github.com/zalando/patroni/issues/894
Fixes: https://github.com/zalando/patroni/issues/951

### CODE REVIEW

**Comment by redbaron** [comment]
what is the consequence for PG10 users without this patch ?

**Comment by CyberDem0n** [comment]
The same as for pg11, pg_rewind will not work in some cases. But if you haven't seen exceptions similar to the #894 and #951, you are probably fine.

I didn't fugured out yet what exactly triggers the problem, because for example when I am doing a local testing with postgres running on localhost everything seems to be fine with following pg_hba:
```
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     md5
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     md5
host    replication     all             127.0.0.1/32            md5
host    replication     all             ::1/128                 md5

host replication replicator 127.0.0.1/32 md5
host all all 0.0.0.0/0 md5
```

Superuser name is postgres in my case and replication user is replicator

**Comment by CyberDem0n** [comment]
After a bit more investigation I've figured out why it happens on 10+.

If we are opening replication connection with replication=database option instead of replication=1, postgres will accept it with `host all ...` or `host postgres ...` line in the pg_hba. `host replication ...` will not accept it, because it works exclusively for replication=1 case.

Basically you can mitigate the problem by adding one more line to pg_hba.

**Comment by mhagander** [comment]
I can confirm running into this, and that the workaround with an extra line in pg_hba.conf works fine.

**Comment by mbanck** [comment]
It took me hours the other day to figure out what was wrong with my pg_hba on v11, so +1 for this PR. I've since pulled it into the Debian package.

**Pull request merged**
