### PR TITLE
Bump Postgres version in Dockerfile to 14

### PR DESCRIPTION
**Pull request by lvjonok**
I tried to use your tool and encountered error, when tried to build Dockerfile

Problem seemed to be in missing dependency on setuptools. After adding it, everything built properly

### CODE REVIEW

**Review by CyberDem0n — CHANGES_REQUESTED** [review]
Sorry, but no. Just bump `PG_MAJOR` to 14 at the top of the Dockerfile and everything will work.
Version 10 is nearly 5 years old and will become EOL in November 2022.

**Comment by lvjonok** [comment]
Thank you, it worked!

Anyway, I updated default argument of ```PG_MAJOR```, so next people will not have this problem again.

**Comment by sdudoladov** [comment]
:+1:

**Comment by CyberDem0n** [comment]
:+1:

**Review by CyberDem0n — APPROVED** [review]

**Pull request merged**
