### PR TITLE
Use postgres:9.6 as a base image

### PR DESCRIPTION
**Pull request by CyberDem0n**
* Don't install zookeeper
* Use latest version of etcd
* Expose 5000 and 5001 on corresponding ports

### CODE REVIEW

**Comment by alexeyklyukin** [comment]
👍

**Comment by a1exsh** [comment]
I wonder why did we have zookeeper package installed at all: only for the client part?

**Comment by CyberDem0n** [comment]
Because https://github.com/zalando/patroni/blob/master/docker/entrypoint.sh supports zookeeper as well

**Comment by a1exsh** [comment]
@CyberDem0n so now it doesn't? ;)  Honestly, I'm lost.  There are 4 changes in this PR one not related to the other in any way, or I just fail to see a relation.

**Comment by CyberDem0n** [comment]
Zookeeper is not needed for testing/demoing stuff, but stripping it out from entrypoint.sh also doesn't make much sense.

**Comment by CyberDem0n** [comment]
:+1:

**Pull request merged**
