### PR TITLE
Make it possible to provide datacenter configuration for Consul

### PR DESCRIPTION
**Pull request by DeathBorn**
Consul has datacenter configuration.

### CODE REVIEW

**Comment by DeathBorn** [comment]
This configuration works
```
consul:
  url: http://consul.host:8500
  token: long-token-here
  dc: dev1-d1

**Comment by CyberDem0n** [comment]
:+1:

**Comment by CyberDem0n** [comment]
Oh, it seems I've forgot to add it into 'consul.py' :(

**Comment by alexeyklyukin** [comment]
👍

**Comment by CyberDem0n** [comment]
Merged, thank you!

**Comment by DeathBorn** [comment]
Oh :) thank you for this tool.

**Pull request merged**
