### PR TITLE
Decode output from wal-e list backup

### PR DESCRIPTION
**Pull request by feikesteenbergen**
When running this script using Python3, the output is bytestring instead of string.
We explicitly decode it to ensure checks further down are ok.

The trigger for this patch is:

```
ERROR: unable to get some of WALE backup parameters: 'expanded_size_bytes'
```

### CODE REVIEW

**Comment by alexeyklyukin** [comment]
👍

**Comment by CyberDem0n** [comment]
Tests with python3 are failing

**Comment by CyberDem0n** [comment]
:+1:

**Comment by feikesteenbergen** [comment]
👍

**Pull request merged**
