### PR TITLE
Handle exceptions raised from psutil

### PR DESCRIPTION
**Pull request by CyberDem0n**
Process.cmdline can raise `NoSuchProcess` or `AccessDenied`
Process.children can raise `AccessDenied`

Fixes https://github.com/zalando/patroni/issues/609

### CODE REVIEW

**Comment by CyberDem0n** [comment]
@ants, what do you think?

**Comment by ants** [comment]
Looks good.

I had an academic question about what is the correct behavior when accessing a childs command line gives AccessDenied, for safety we should then fall back to waiting on the postmaster before triggering safepoint. But I don't see how AccessDenied (EPERM, EACCESS) can even happen when checking a processes commandline so I guess it's not even worth worrying about.

**Comment by CyberDem0n** [comment]
👍

**Comment by alexeyklyukin** [comment]
👍

**Pull request merged**
