### PR TITLE
Env var of PATRONI_RESTAPI_CONNECT_ADDRESS and PATRONI_POSTGRESQL_CON…

### PR DESCRIPTION
**Pull request by devopsy-ir**
…NECT_ADDRESS to make available on diffrent vms and posrts

### CODE REVIEW

**Comment by CyberDem0n** [comment]
@devopsy-ir have you seen the comment? https://github.com/zalando/patroni/blob/b31a4d55c9c628c6489a2c2bd7be1d0611577ead/Dockerfile#L1-L2

**Comment by devopsy-ir** [comment]
> @devopsy-ir have you seen the comment?
> 
> https://github.com/zalando/patroni/blob/b31a4d55c9c628c6489a2c2bd7be1d0611577ead/Dockerfile#L1-L2

Yes, you are true. But what about multi node deployment?

**Comment by CyberDem0n** [comment]
> Yes, you are true. But what about multi node deployment?

These Dockerfile, entrypoint, and docker-compose are to play with Patroni _locally_ and never meant for anything other than that.

**Comment by devopsy-ir** [comment]
> > Yes, you are true. But what about multi node deployment?
> 
> These Dockerfile, entrypoint, and docker-compose are to play with Patroni _locally_ and never meant for anything other than that.

What is the prolem of reading this variables from env var of os?!!

**Pull request closed without merging**
