### PR TITLE
Release v3.2.2

### PR DESCRIPTION
**Pull request by CyberDem0n**
- update release notes
- bump Patroni version
- bump pyright version and fix reported issues
- improve compatibility with legacy psycopg2

### CODE REVIEW

**Review by barthisrael — APPROVED** [review]

**Comment by barthisrael** [comment]
👍

**Comment by barthisrael** [comment]
Just a side comment: it seems we are missing to cherry-pick the `pending_restart` stuff into `REL_3_2`.

**Comment by CyberDem0n** [comment]
It is cherry-picked, I just forgot to push `REL_3_2`.

**Comment by hughcapet** [comment]
👍

**Pull request merged**
