### PR TITLE
Consider node not healthy if it is not on the latest timeline

### PR DESCRIPTION
**Pull request by CyberDem0n**
The latest timeline is calculated from the `/history` key in DCS. In case there is no such key or it contains some garbage we consider the node healthy.

Hopefully fixes https://github.com/zalando/patroni/issues/890

### CODE REVIEW

**Comment by bradnicholson** [comment]
I took a look and tested it out.  It correctly detects the timeline divergence here:
https://github.com/zalando/patroni/blob/76f4bc286d898e5f810e4747df81f35e362ca2c0/patroni/ha.py#L560

It prevents failing over, but it doesn't log correctly.  It logs:

`INFO: following a different leader because i am not the healthiest node`

There is no other leader running at this time.

**Comment by CyberDem0n** [comment]
You are right, the [message](https://github.com/zalando/patroni/blob/76f4bc286d898e5f810e4747df81f35e362ca2c0/patroni/ha.py#L852) is sometimes misleading, and it logs the same for all cases when Patroni decided that this node isn't healthy enough to become the new primary.
The problem is that we are in a dynamic environment, not having other nodes at the moment doesn't mean that some of them won't become available in a couple of seconds.

I can add more verbose logs in the place where the node tries to determine whether it is the healthiest or not, something similar to what we have here: https://github.com/zalando/patroni/blob/76f4bc286d898e5f810e4747df81f35e362ca2c0/patroni/ha.py#L576-L594

**Comment by bradnicholson** [comment]
I think that would be helpful.  I think the behavior is fine (including the message it is logging), but knowing that it is also failing because of the timeline issue in the case when the other member doesn't come back would be useful.

**Comment by bradnicholson** [comment]
Thanks.  This looks good to me.

**Comment by jberkus** [comment]
@CyberDem0n I'd like the ability to turn off this functionality via a configure switch.

In cases where all nodes on the latest timeline are *gone*, I may want the ability to start up from an older surviving node if I'm willing to live with the data loss.  In fact, I know at least two production clusters where I *do* want that.

**Comment by jberkus** [comment]
... and for that matter, considering the number of ways that this can fail and wedge the cluster, I'd argue that timeline switch detection should never be on by default.

**Comment by CyberDem0n** [comment]
I tend to agree with @jberkus, it should configurable and not be enabled by default.
@jberkus, @bradnicholson, @ants, @sfrost, @dwsteele, what would be the good name for such switch?

**Comment by bradnicholson** [comment]
Favoring availability over data loss is the correct tradeoff with Patroni (with that being controllable via amounts of data loss you will tolerate, or just using sync rep if you want none).  

That said, if that failover can break the consistency of the archive, that seems a bit more nuanced to me.  pgBackRest is catching these issues via checksumming, but other backup tools may not.  

Whether we act or not (or how) on this case is an open question, but silently breaking the archive seems like a really bad behavior.

**Comment by dwsteele** [comment]
Agreed, but I think appending the target timeline to the .partial files and prioritizing .history files will take care of most of the issues that we've seen.

I'm pretty confident that both patches will make their way into Postgres.  If they don't get back-patched then we'll "backpatch" them in pgBackRest.

I don't have any good solution for the situation where two clusters end up on the same timeline.  Prioritizing .history files will help, but it won't eliminate the problem entirely.  The patch under review will also help when it is enabled, but it is not perfect, either.

**Comment by bradnicholson** [comment]
Seems prudent to wait on this until we see what happens with PG.

If they get back patched, the right approach seems to be do nothing with Patroni, except perhaps a mention in the docs that for archiving to be reliable, one must run versions >= x,y,z for PG.

**Comment by CyberDem0n** [comment]
@bradnicholson in the last [commit](https://github.com/zalando/patroni/pull/892/commits/b50d7af5148bb5c8ba23597a49232c39e12146d8) I introduced the new configuration parameter, `check_timeline`, which is set to `false` by default.

I am planning to merge this PR and maybe wrap the new release. What do you think?

**Pull request merged**
