### PR TITLE
Fix race condition when opening connection to cluster

### PR DESCRIPTION
**Pull request by CyberDem0n**
`Postgresql.connection` method could be called from different threads at the same time resulting in more than one connection open but only one used afterwards.

### CODE REVIEW

**Comment by alexeyklyukin** [comment]
👍

**Comment by alexeyklyukin** [comment]
Do we possibly have the same issue with the _cursor() method? IIRC the DB query code calls the cursor as well if there is no cursor, and since it may be called concurrently, the first invocation result can be overwritten by a subsequent ones.

**Comment by CyberDem0n** [comment]
_cursor doesn't have this problem, it is called only from main thread

**Comment by CyberDem0n** [comment]
:+1:

**Pull request merged**
