### PR TITLE
93compat

### PR DESCRIPTION
**Pull request by jberkus**
Makes replication slots optional (controlled by the configuration option "use_slots").  This allows Patroni to be used with 9.3.

### CODE REVIEW

**Comment by jberkus** [comment]
I'm confused.  The check above says it failed, but when I look at the travis report, all 83 tests passed.  What am I missing?

**Comment by CyberDem0n** [comment]
flake8 doesn't like some changes:

$ python setup.py flake8

running flake8
helpers/postgresql.py:46:1: W293 blank line contains whitespace
helpers/postgresql.py:261:121: E501 line too long (121 > 120 characters)
helpers/postgresql.py:367:121: E501 line too long (127 > 120 characters)

The command "python setup.py flake8" exited with 1.

**Comment by jberkus** [comment]
Sigh, really?

Anyway, spacing changes submitted.

**Comment by jberkus** [comment]
What's going on with the in_healthiest_node test?  I didn't touch any of that code.

**Comment by jberkus** [comment]
OK, I fixed one bug: The original code for is_healthiest_node contains '0/0000000', which isn't a valid LSN, but '0/0000000'::pg_lsn seems to work anyway, whereas it doesn't work with pg_xlog_location_diff.  However, the test is still failing for reasons I can't see.  Suggestions?

**Comment by CyberDem0n** [comment]
flake8 might be sounds silly but sometimes it really helps. For example it also reports unused variables.

Don't waste your time. I will fix failing test later. Purpose of unit tests in our case is to go through as much as possible code-paths. But we are not running queries against real databases, tests just mock some methods of psycopg2 and depending on query itself and other parameters return some expected values.

**Comment by CyberDem0n** [comment]
There is one "feature" I'd like to have.
I think `use_slots` option in config file should not be mandatory and by default we must assume that it is turned 'on'. 

- self.use_slots = config['use_slots']
+ self.use_slots = config.get('use_slots', True)


Besides this everything else looks fine.

**Comment by jberkus** [comment]
Ah, I wasn't sure that config_get() worked that way; I'm more used to ConfigObj.  Yeah, that makes sense.

**Comment by jberkus** [comment]
Yah, FYI, all tests pass on a docker image with 9.3 installed ... and use_slots set to yes!

**Comment by jberkus** [comment]
Mostly I get really aggrivated with pep8/flake8 making me reformat my SQL strings in really ridiculous ways.

**Pull request merged**
